clickhouse:
  # Clickhouse configuration
  # Clickhouse host
  host: "111.64.3.200:9000"
  # Clickhouse username
  username: ""
  # Clickhouse password
  password: ""
  # Default database
  database: "k2c"
kafka:
  # Kafka configuration
  # Kafka host
  host:
    - "111.64.3.200:9092"
core:
  files:
    appone:
      enabled: true
      topics:
        - "my_topic"
    apptwo:
      enabled: true
      topics:
        - "my_topic2"